name: CI
on: [push]

jobs:
  install:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - if: matrix.os == 'macos-latest'
        run: brew install scala sbt
      - run: |
          sbt lonerJVM/test lonerJS/test
